{
 "title": "Prometheus vs. VictoriaMetircs resource comparison",
 "description": "Following dashboards provide easy comparison between Promethues pod and VictoriaMetrics Virtual machine stats",
 "tags": [
  "prometheus",
  "victoriametrics"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "The following dashboard shows used CPUs cores in a rate of 5 minutes for all possible modes except idle",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"infrastructure\", pod=\"prometheus-kube-prometheus-stack-prometheus-0\", container=\"prometheus\", cluster=\"\"}) by (container)",
     "legendFormat": "prometheus"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{job=\"victoriametrics-poc-sm\", instance=\"172.17.197.246:9100\", mode!=\"idle\"}[5m]))",
     "legendFormat": "victoriametrics"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "description": "The following panel show used memory for process",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"infrastructure\", pod=\"prometheus-kube-prometheus-stack-prometheus-0\", container=\"prometheus\"}",
     "legendFormat": "prometheus"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"victoriametrics-poc-sm\", instance=\"172.17.197.246:9100\"} - node_memory_MemAvailable_bytes{job=\"victoriametrics-poc-sm\", instance=\"172.17.197.246:9100\"}",
     "legendFormat": "victoriametrics"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "description": "The following panel shows used disk space by instance",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"infrastructure\", persistentvolumeclaim=\"prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"infrastructure\", persistentvolumeclaim=\"prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0\"})\n)\n",
     "legendFormat": "prometheus"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"victoriametrics-poc-sm\", instance=\"172.17.197.246:9100\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"victoriametrics-poc-sm\", instance=\"172.17.197.246:9100\", mountpoint=\"/\"}",
     "legendFormat": "victoriametrics"
    }
   ]
  },
  {
   "title": "Network input",
   "type": "graph",
   "description": "Network input bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"infrastructure\", pod=~\"prometheus-kube-prometheus-stack-prometheus-0\"}[5m])) by (pod)",
     "legendFormat": "prometheus"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"172.17.197.246:9100\",device=~\"(?i)^(ens|eth).+$\"}[5m])",
     "legendFormat": "victoriametrics"
    }
   ]
  },
  {
   "title": "Network output",
   "type": "graph",
   "description": "Network output bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"infrastructure\", pod=~\"prometheus-kube-prometheus-stack-prometheus-0\"}[5m])) by (pod)",
     "legendFormat": "prometheus"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"172.17.197.246:9100\",device=~\"(?i)^(ens|eth).+$\"}[5m])",
     "legendFormat": "victoriametrics"
    }
   ]
  }
 ]
}